version: '3'
services:
  app:
    container_name: docker-node-mysql
    restart: always
    build: .
    ports: 
      - '80:8080'
      # links:
      #   - mysql
  # mysql:
  #   container_name: mysql
  #   image: mysql
  #   ports: 
  #     - '3306:3306'